# Basic Information 
title: Yanfu Yan
position: Ph.D. Student
affiliation: William & Mary, USA 
affiliation_link: https://cs.jhu.edu/
affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: yyan09 (at) wm.edu
email2: yanyanfu1021 (at) gmail.com

# Search Engine Optimization (SEO)
keywords: yanfu yan, yan yanfu, yanfu yan, yanfu
canonical: 
description: Yanfu Yan is a Ph.D. student at William & Mary, USA. His research lies in meta-learning, incremental learning, and image generation.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=M-bzdRoAAAAJ&hl=zh-CN
github_link: https://github.com/yanyanfu
linkedin: https://www.linkedin.com/in/liuyaoyao/
twitter: 

# Images 
avatar: ./assets/img/profile.png
favicon: 
favicon_dark: 

# Footnotes
footnote: 
footnote_link: 

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
